### ISSUE TITLE
Could you please provide an example of how to use it

### ISSUE THREAD

**Issue by wanliyunyan** [aimalygin/LibXray#1]
Thank you very much for providing the library. Could you please provide an example of how to use it? I really need it, thank you.

**Comment by aimalygin** [comment]
> Thank you very much for providing the library. Could you please provide an example of how to use it? I really need it, thank you.

Firstly, you have to use PacketTunnelProvider.
Second thing that you have to use is any tun2sock tools, for example, [Tun2SocksKit](https://github.com/EbrahimTahernejad/Tun2SocksKit).
Then inside the PacketTunnelProvider class, the code will look like this:
1) Run the socks tunnel
```
DispatchQueue.global(qos: .userInitiated).async {
      let result = Socks5Tunnel.run(withConfig: Socks5Tunnel.Config.file(path: self.configManager.socks5ConfigUrl))
}
```
2) Run xray
```
let runRequest = RunXrayRequest(datDir: nil, configPath: configManager.xrayConfigPath, maxMemory: 0)
result = LibXrayRunXray(runRequest.toBase64String())
```
You have to do that inside the method:
`func startTunnel(options: [String: NSObject]? = nil, completionHandler: @escaping (Error?) -> Void)`

**Comment by wanliyunyan** [comment]
Thank you for your reply. I think I still have a lot of experiments to do

**Comment by aimalygin** [comment]
> Thank you for your reply. I think I still have a lot of experiments to do

Also, I think it is helpful for you, this is tun2sock config example:
```
let config = """
        tunnel:
          mtu: \(ConfigManager.mtu)
        socks5:
          port: \(port)
          address: ::1
          udp: 'udp'
        misc:
          task-stack-size: 20480
          connect-timeout: 5000
          read-write-timeout: 60000
          log-file: stderr
          log-level: none
          limit-nofile: 65535
        """
```
This port is the inbound port for xray you must use in the xray config.
The scheme of work looks so:
1) tun2sock is proxying the traffic to the localhost to your specified port.
2) LibXray listens to the port and proxy the traffic to the destination
